apiVersion: apps/v1
kind: Deployment
metadata:
  name: website3
spec:
  selector:
    matchLabels:
      app: website3
  replicas: 1
  template:
    metadata:
      labels:
        app: website3
    spec:
      containers:
      - name: website3
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wp2-data
          subPath: wp-sites/website3
          mountPath: /var/www/html
      volumes:
      - name: wp2-data
        nfs:
          path: /aamir
          server: 192.168.200.150
---
apiVersion: v1
kind: Service
metadata:
  name: website3
spec:
  type: NodePort
  selector:
    app: website3
#    department: sales
  ports:
  - protocol: TCP
    port: 80
